spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/crypto_chat}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop} # Для продакшена лучше использовать 'validate' через переменную окружения
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: crypto-project

app:
  jwtSecret: ${JWT_SECRET:YourSuperSecretKeyForCryptoProjectChangeThis} # На сервере эта переменная должна быть установлена
  jwtExpirationInMs: 86400000 # Время жизни токена в миллисекундах (здесь 24 часа)
